poll_interval_secs = 300
notify_on_first_run = true
state_path = "/app/data/state.json"
webhook_url = ""
discord_username = "Hakuren-Bot"

[[watch]]
urlname = "kokuren888"

[[youtube]]
channel = "@kokuren_3rd"
