services:
  hakuren-bot:
    container_name: Hakuren-Bot
    build: .
    image: hakuren-bot
    restart: unless-stopped
    env_file: .env
    environment:
      RUST_LOG: hakuren_bot=info
    volumes:
      - ./data:/app/data
